name: Fahkap
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  antdesign_icons: ^0.0.3
  autocomplete_textfield: null
  badges: ^2.0.2
  cached_network_image: ^2.4.0
  carousel_slider: ^3.0.0
  chewie: ^1.0.0
  connectivity: ^3.0.6
  cron: null
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  data_connection_checker: null
  dio: any
  filesystem_picker: ^1.0.3
  flutter:
    sdk: flutter
  flutter_local_notifications: null
  flutter_spinkit: any
  flutter_staggered_grid_view: ^0.4.0 
  font_awesome_flutter: ^9.1.0
  get: 4.5.1
  get_storage: any
  image_cropper: any
  image_picker: any
  internet_connection_checker: ^0.0.1+3
  intl: null
  intl_phone_field: ^2.0.1
  jwt_decode: null
  open_file: null
  page_view_indicator: any
  path_provider: any
  pdf: any
  permission_handler: any
  provider: ^5.0.0
  qr_flutter: ^4.0.0
  rating_bar: ^0.2.0
  screenshot: ^1.2.3
  share: ^2.0.4
  shimmer: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  splashscreen: ^1.3.5
  sqflite: ^2.0.0+3
  syncfusion_flutter_pdf: ^18.4.47-beta
  theme_provider: any
  flutter_svg: any
  toast: ^0.1.5
  video_player: ^2.0.0 
  smooth_star_rating_null_safety: ^1.0.4+2
  share_plus: 
  # flutter_downloader:  any
  flutter_mobx : any
  webview_flutter: ^2.0.13
  uni_links: ^0.5.0
dev_dependencies:
  flutter_launcher_icons: ^0.8.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
flutter:
  fonts:
    - family: OpenSan
      fonts:
        # - asset: fonts/Open_Sans/static/OpenSans_Condensed/OpenSans_Condensed-Light.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_Condensed/OpenSans_Condensed-Regular.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_Condensed/OpenSans_Condensed-Medium.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_Condensed/OpenSans_Condensed-SemiBold.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_Condensed/OpenSans_Condensed-Bold.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_Condensed/OpenSans_Condensed-ExtraBold.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_SemiCondensed/OpenSans_SemiCondensed-Light.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_SemiCondensed/OpenSans_SemiCondensed-Regular.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_SemiCondensed/OpenSans_SemiCondensed-Medium.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_SemiCondensed/OpenSans_SemiCondensed-SemiBold.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_SemiCondensed/OpenSans_SemiCondensed-Bold.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_SemiCondensed/OpenSans_SemiCondensed-ExtraBold.ttf
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-Light.ttf
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-Regular.ttf
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-Medium.ttf
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-SemiBold.ttf
        # - asset: fonts/Open_Sans/static/OpenSans/OpenSans-Bold.ttf
        # - asset: fonts/Open_Sans/static/OpenSans/OpenSans-ExtraBold.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_Condensed/OpenSans_Condensed-LightItalic.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_Condensed/OpenSans_Condensed-Italic.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_Condensed/OpenSans_Condensed-MediumItalic.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_Condensed/OpenSans_Condensed-SemiBoldItalic.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_Condensed/OpenSans_Condensed-BoldItalic.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_Condensed/OpenSans_Condensed-ExtraBoldItalic.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_SemiCondensed/OpenSans_SemiCondensed-LightItalic.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_SemiCondensed/OpenSans_SemiCondensed-Italic.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_SemiCondensed/OpenSans_SemiCondensed-MediumItalic.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_SemiCondensed/OpenSans_SemiCondensed-SemiBoldItalic.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_SemiCondensed/OpenSans_SemiCondensed-BoldItalic.ttf
        # - asset: fonts/Open_Sans/static/OpenSans_SemiCondensed/OpenSans_SemiCondensed-ExtraBoldItalic.ttf
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-LightItalic.ttf
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-Italic.ttf
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-MediumItalic.ttf
    - family: orkney
      fonts:
        - asset: assets/police/orkney-bold.otf
        - asset: assets/police/orkney-light.otf
        - asset: assets/police/orkney-medium.otf
        - asset: assets/police/orkney-regular.otf
  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec
  # The following section is specific to Flutter.
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/logo.png
    - assets/images/error.gif
    - assets/om.png
    - assets/logo.png
    - assets/login.png
    - assets/bus.png
    - assets/register.png
    - assets/busVoyage.png
    - assets/payement/om.png
    - assets/payement/momo.png
    - assets/payement/paycard.png 
    - assets/svg_icones/user.svg
    - assets/svg_icones/callreceive.svg
    - assets/svg_icones/mapTagUser.svg
    - assets/svg_icones/onbo1.png
    - assets/svg_icones/onbo2.png
    - assets/svg_icones/onbo3.png
    - assets/svg_icones/logImg.png
    - assets/svg_icones/logUser1.svg
    - assets/svg_icones/shoppingCart.svg
    - assets/svg_icones/refresh.svg
    - assets/svg_icones/home.svg
    - assets/svg_icones/bagmoney.svg
    - assets/svg_icones/phone_mobile.svg
    - assets/svg_icones/key.svg
    - assets/svg_icones/grid1.svg
    - assets/svg_icones/grid2.svg
    - assets/images/shop1.png
    - assets/images/shop2.png

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
